import os
import smtplib
import pandas as pd
import yfinance as yf

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# =====================================
# 股票池（可自行增加）
# =====================================

TICKERS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "META",
    "GOOGL",
    "TSLA",
    "AMD",
    "AVGO",
    "NFLX"
]

# =====================================
# 評分函數
# =====================================

def score_stock(ticker):

    try:
        df = yf.download(
            ticker,
            period="3mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if len(df) < 30:
            return None

        close = df["Close"]
        volume = df["Volume"]

        ma20 = close.rolling(20).mean()

        current_price = close.iloc[-1]

        momentum_5d = (
            current_price / close.iloc[-6] - 1
        )

        trend = (
            current_price / ma20.iloc[-1] - 1
        )

        avg_volume = volume.rolling(20).mean().iloc[-1]

        volume_ratio = (
            volume.iloc[-1] / avg_volume
            if avg_volume > 0 else 1
        )

        score = (
            momentum_5d * 40 +
            trend * 40 +
            (volume_ratio - 1) * 20
        )

        return {
            "Ticker": ticker,
            "Score": round(score, 2),
            "Price": round(float(current_price), 2),
            "Momentum": round(momentum_5d * 100, 2),
            "Trend": round(trend * 100, 2),
            "VolumeRatio": round(volume_ratio, 2)
        }

    except Exception as e:
        print(f"Error processing {ticker}: {e}")
        return None


# =====================================
# Email內容
# =====================================

def build_email_body(top3_df):

    body = """
🔥 DAILY TOP 3 STOCK PICKS

以下為今日評分最高股票：

"""

    rank = 1

    for _, row in top3_df.iterrows():

        body += f"""
#{rank} {row['Ticker']}

Price: ${row['Price']}
Score: {row['Score']}
5D Momentum: {row['Momentum']}%
Trend vs MA20: {row['Trend']}%
Volume Ratio: {row['VolumeRatio']}

--------------------------------

"""

        rank += 1

    body += "\nGenerated by GitHub Actions"

    return body


# =====================================
# 發送Email
# =====================================

def send_email(subject, body):

    email_user = os.environ["EMAIL_USER"]
    email_password = os.environ["EMAIL_PASSWORD"]
    email_to = os.environ["EMAIL_TO"]

    msg = MIMEMultipart()

    msg["From"] = email_user
    msg["To"] = email_to
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(email_user, email_password)
        server.send_message(msg)

    print("Email sent successfully")


# =====================================
# 主程式
# =====================================

def main():

    print("Scanning stocks...")

    results = []

    for ticker in TICKERS:

        result = score_stock(ticker)

        if result:
            results.append(result)

    if len(results) == 0:
        print("No data found")
        return

    df = pd.DataFrame(results)

    top3 = (
        df.sort_values(
            by="Score",
            ascending=False
        )
        .head(3)
    )

    print("\nTop 3 Stocks")
    print(top3)

    email_body = build_email_body(top3)

    send_email(
        "📈 Daily Top 3 Stock Picks",
        email_body
    )


if __name__ == "__main__":
    main()
